# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Criptonita' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod  'SnapKit', '~> 5.0.0'
  pod 'Alamofire', '~> 4.0'
  pod 'ModuloSuporte', :git => 'https://github.com/bittencourthiago/ModuloSuporte.git'
  pod 'AlamofireImage'
  pod 'SwiftLint'

  # Pods for Criptonita

  target 'CriptonitaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CriptonitaUITests' do
    # Pods for testing
  end

end
